# Generated by Django 5.0 on 2023-12-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=155)),
                ('lastname', models.CharField(max_length=155)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
    ]
